require("options")
require("keymaps")
require("plugins-setup")

require("plugins.colorscheme")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.treesitter")

require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")
