require("plugins-setup")
require("options")
require("keymaps")

require("plugins.nvim-cmp")
require("plugins.colorscheme")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.gitsigns")

require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")
